ID-B-4.1 - ID-B-4.3
initaIe/KindPaws pull request #5
Opened 2024-09-29 11:27 UTC by initaIe

2024-09-29 17:03 UTC, KirillSachkov requested changes

2024-09-29 17:03 UTC, KirillSachkov commented on KindPaws.Backend/src/KindPaws.Domain/Managements/BreedManagement/ValuseObjects/BreedColor.cs
> +    public string Value { get; private set; }
У VO не должно быть вообще сеттеров, нельзя изменять их состояние, только полная замена. Если в других VO есть такая же проблема, нужно исправить

2024-09-29 17:03 UTC, KirillSachkov commented on KindPaws.Backend/src/KindPaws.Domain/Managements/PetManagement/ValueObjects/BiometricDetails.cs
> +    public float Height { get; private set; }
без сеттеров

2024-09-29 17:03 UTC, KirillSachkov commented on KindPaws.Backend/src/KindPaws.Domain/Managements/SpecieManagement/AggregateRoot/Specie.cs
> +    public IReadOnlyList<Pet> Pets => _pets;
Вид не должен иметь прямых ссылок на сущности в других агрегатах. У нас есть агрегат волонтеров и агрегат видов, они не должны пересекаться таким образом. У Pet есть SpeciesId, это максимум что можно себе позволить

2024-09-29 17:03 UTC, KirillSachkov commented on KindPaws.Backend/src/KindPaws.Infrastructure/ApplicationDbContext.cs
> +    public DbSet<Pet> Pets => Set<Pet>();
Не должно быть dbset животных и пород. Животными мы управляем только через агрегат рут - Volunter. Породами мы управляем только через виды. Поэтому здесь нужно оставить только волонтеров и виды, два агрегата

2024-09-29 19:32 UTC, initaIe commented on KindPaws.Backend/src/KindPaws.Infrastructure/ApplicationDbContext.cs
> +    public DbSet<Pet> Pets => Set<Pet>();
Если мы управляем через AggregatesRoot Volunteer и Specie занчит у меня структура пакетов не правильная? Надо убрать BreedManagement и PetManagement и оставить VolunteerManagement и SpecieManagement? А Pet поместить в VolunteersManagment/Entities/Pet.cs, а Breed в SpeciesManagement/Entities/Breed.cs?

2024-09-29 19:36 UTC, initaIe commented on KindPaws.Backend/src/KindPaws.Domain/Managements/SpecieManagement/AggregateRoot/Specie.cs
> +    public IReadOnlyList<Pet> Pets => _pets;
Я правильно понимаю что у Volunteer храним List Pets, у Pets: VolunteerId + Volunteer, SpecieId + Specie, BreedId + Breed, у Specie: List Breeds, у Breed: SpecieId + Specie?

2024-09-30 08:07 UTC, KirillSachkov commented on KindPaws.Backend/src/KindPaws.Domain/Managements/SpecieManagement/AggregateRoot/Specie.cs
> +    public IReadOnlyList<Pet> Pets => _pets;
У волонтера нужно оставить только Pets. У Pets не нужна ссылка на волонтера, потому что мы и так всегда будет знать волонтера животного, потому что мы управляем ими через волонтера. Также у Pets мы можем иметь максимум id других агрегатов, то есть максимум SpeciesId и BreedId. У Species должны быть Breeds. У Breeds ничего

2024-09-30 08:07 UTC, KirillSachkov commented on KindPaws.Backend/src/KindPaws.Infrastructure/ApplicationDbContext.cs
> +    public DbSet<Pet> Pets => Set<Pet>();
Да, нужно убрать BreedManagement и PetManagement и оставить VolunteerManagement и SpeciesManagement. Да, всё верно

2024-09-30 08:08 UTC, KirillSachkov approved these changes

2024-09-30 09:29 UTC, merged