ID-B-4.4
initaIe/KindPaws pull request #6
Opened 2024-09-29 21:14 UTC by initaIe

2024-09-30 07:48 UTC, YADARAN1 requested changes

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/BreedManagement/ValueObjects/BreedColor.cs
> +    public BreedColor()
У VO должен быть 1 конструктор

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/PetManagement/ValueObjects/Disease.cs
> +    public Disease()
1 конструктор

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/PetManagement/ValueObjects/HealthDetails.cs
> +    public HealthDetails()
1 конструктор

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/PetManagement/ValueObjects/HealthDetails.cs
> +    public HealthDetails(
Приватный

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/PetManagement/ValueObjects/HealthStatus.cs
> +    public HealthStatus()
1 конструктор

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/PetManagement/ValueObjects/PetPhoto.cs
> +    public PetPhoto()
1 конструктор

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/PetManagement/ValueObjects/Requisite.cs
> +    public Requisite()
1 конструктор

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/PetManagement/ValueObjects/PetType.cs
> +    public PetType()
1 конструктор

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/PetManagement/ValueObjects/PetType.cs
> +    public PetType(SpecieId specieId, BreedId breedId)
Приватный

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/PetManagement/ValueObjects/SupportDetails.cs
> +    public SupportDetails()
1 конструктор

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/PetManagement/ValueObjects/SupportDetails.cs
> +    public SupportDetails(
Приватный

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/PetManagement/ValueObjects/SupportStatus.cs
> +    public SupportStatus()
1 конструктор

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/PetManagement/ValueObjects/Vaccine.cs
> +    public Vaccine()
1 конструктор

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/VolunteerManagement/ValueObjects/EmailAddress.cs
> +    public EmailAddress()
1 конструктор

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/VolunteerManagement/ValueObjects/Lists/SocialNetworkList.cs
> +    public SocialNetworkList(List<SocialNetwork> socialNetworks)
Приватный конструктор

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/VolunteerManagement/ValueObjects/SocialNetwork.cs
> +    public SocialNetwork()
1 конструктор

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Managements/VolunteerManagement/ValueObjects/SocialNetwork.cs
> +    public SocialNetwork(
приватный

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Shared/ValueObjects/Address.cs
> +    public Address()
1 конструктор

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Shared/ValueObjects/Age.cs
> +    public Age()
1 конструктор

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Domain/Shared/ValueObjects/Gender.cs
> +    public Gender()
1 конструктор

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Infrastructure/ApplicationDbContext.cs
> +        optionsBuilder.UseLoggerFactory(CreateFactory());
Добавь ещё EnableSensetiveDataLogging

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Infrastructure/Configurations/BreedConfiguration.cs
> +        builder.HasKey(breed => breed.Id);
Добавь названия таблицам в snakecase стиле

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Infrastructure/Configurations/BreedConfiguration.cs
> +        builder.HasKey(breed => breed.Id);
И каждому параметру название колонки в бд

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Infrastructure/Configurations/PetConfiguration.cs
> +        builder.HasKey(pet => pet.Id);
Название таблицы

2024-09-30 07:48 UTC, YADARAN1 commented on KindPaws.Backend/src/KindPaws.Infrastructure/Configurations/SpecieConfiguration.cs
> +
Название таблицы

2024-09-30 09:51 UTC, initaIe commented on KindPaws.Backend/src/KindPaws.Domain/Managements/PetManagement/ValueObjects/HealthDetails.cs
> +    public HealthDetails()
EF Core требует в многих VO наличие пустого конструктора при создании миграции

2024-09-30 10:06 UTC, initaIe commented on KindPaws.Backend/src/KindPaws.Domain/Managements/PetManagement/ValueObjects/PetType.cs
> +    public PetType(SpecieId specieId, BreedId breedId)
В 2-ух местах с фабричным методом пропустил, да.. Там нужен приватный конструктор. А где нет валидации и фабричного статического метода зачем приватный конструктор?

2024-10-01 05:57 UTC, YADARAN1 requested changes
Видел комментарий, частая ошибка, возникает она, потому-что есть разные названия в VO, ef core не может смаппить их, поменяй во всех VO названия, которые ты передаёшь в конструктор, они должны быть такими же, как и свойства.

2024-10-01 09:10 UTC, merged

2024-10-01 10:23 UTC, initaIe commented
> Видел комментарий,частая ошибка,возникла она,потому-что в ВО есть разные названия, ef core не может смаппить их, поменяй во всех ВО названия,которые ты передаешь в конструктор,они должны быть такими же,как и свойства.

У меня проблема в том, что он просит пустой конструктор в VO с Listами, почитал что "EF Core не поддерживает маппинг для сложных типов". Посмотрел репы других ребят и Кирилла и у них в подобных случаях есть пустые конструкторы.